import { Player, Owner } from './types';

export const INITIAL_OWNERS: Owner[] = [
  { id: 'tech-titans', name: 'Tech Titans', color: '#3b82f6', wallet: 1000000, initialWallet: 1000000 },
  { id: 'product-pirates', name: 'Product Pirates', color: '#f59e0b', wallet: 1000000, initialWallet: 1000000 },
  { id: 'marketing-mavericks', name: 'Marketing Mavericks', color: '#ec4899', wallet: 1000000, initialWallet: 1000000 },
  { id: 'sales-spartans', name: 'Sales Spartans', color: '#10b981', wallet: 1000000, initialWallet: 1000000 },
  { id: 'hr-heroes', name: 'HR Heroes', color: '#8b5cf6', wallet: 1000000, initialWallet: 1000000 },
];

export const INITIAL_PLAYERS: Player[] = [
  {
    id: 'p1',
    name: 'Sarah "Spreadsheet" Sorcerer',
    role: 'Excel & Data Analysis',
    skillRating: 94,
    basePrice: 100000,
    status: 'AVAILABLE',
    photoUrl: '📊',
    gender: 'Female',
    falaLeague: 'First Place',
    stats: { badminton: 85, carroms: 90, cricket: 65, football: 70, tt: 95 }
  },
  {
    id: 'p2',
    name: 'Devon "Friday Deploy" Daredevil',
    role: 'Risk Management & Coding',
    skillRating: 88,
    basePrice: 80000,
    status: 'AVAILABLE',
    photoUrl: '🚀',
    gender: 'Male',
    stats: { badminton: 70, carroms: 85, cricket: 95, football: 90, tt: 60 }
  },
  {
    id: 'p3',
    name: 'Maya "Mute-Mic" Legend',
    role: 'Meeting Etiquette & QA',
    skillRating: 91,
    basePrice: 90000,
    status: 'AVAILABLE',
    photoUrl: '🎙️',
    gender: 'Female',
    falaLeague: 'Second Place',
    stats: { badminton: 90, carroms: 95, cricket: 70, football: 65, tt: 85 }
  },
  {
    id: 'p4',
    name: 'Arjun "Inbox Zero" Hero',
    role: 'Operations & Communication',
    skillRating: 95,
    basePrice: 120000,
    status: 'AVAILABLE',
    photoUrl: '📥',
    gender: 'Male',
    stats: { badminton: 75, carroms: 80, cricket: 98, football: 85, tt: 90 }
  },
  {
    id: 'p5',
    name: 'Chloe "Coffee Chugger" Chen',
    role: 'Speed & Endurance',
    skillRating: 86,
    basePrice: 70000,
    status: 'AVAILABLE',
    photoUrl: '☕',
    gender: 'Female',
    stats: { badminton: 80, carroms: 75, cricket: 60, football: 75, tt: 92 }
  },
  {
    id: 'p6',
    name: 'Alex "Out of Office" Rivera',
    role: 'Work-Life Balance Advisor',
    skillRating: 89,
    basePrice: 90000,
    status: 'AVAILABLE',
    photoUrl: '🌴',
    gender: 'Male',
    falaLeague: 'Third Place',
    stats: { badminton: 65, carroms: 90, cricket: 80, football: 82, tt: 78 }
  },
  {
    id: 'p7',
    name: 'Marcus "Standup" Aurelius',
    role: 'Agile & Scrums',
    skillRating: 87,
    basePrice: 80000,
    status: 'AVAILABLE',
    photoUrl: '💬',
    gender: 'Male',
    stats: { badminton: 88, carroms: 80, cricket: 82, football: 75, tt: 85 }
  },
  {
    id: 'p8',
    name: 'Lucas "Figma Wizard" Designer',
    role: 'Visuals & UI Polish',
    skillRating: 93,
    basePrice: 110000,
    status: 'AVAILABLE',
    photoUrl: '🎨',
    gender: 'Male',
    stats: { badminton: 90, carroms: 85, cricket: 75, football: 70, tt: 92 }
  },
  {
    id: 'p9',
    name: 'Sasha "Direct Message" Ninja',
    role: 'Backchannel Negotiations',
    skillRating: 90,
    basePrice: 90000,
    status: 'AVAILABLE',
    photoUrl: '🥷',
    gender: 'Female',
    stats: { badminton: 85, carroms: 94, cricket: 65, football: 60, tt: 88 }
  },
  {
    id: 'p10',
    name: 'Tom "Ping Pong" Champion',
    role: 'Recreational Officer',
    skillRating: 85,
    basePrice: 60000,
    status: 'AVAILABLE',
    photoUrl: '',
    gender: 'Male',
    falaLeague: 'First Place',
    stats: { badminton: 92, carroms: 80, cricket: 85, football: 78, tt: 99 }
  },
  {
    id: 'p11',
    name: 'Rachel "PowerPoint" Princess',
    role: 'Pitch & Presentation',
    skillRating: 92,
    basePrice: 100000,
    status: 'AVAILABLE',
    photoUrl: '📊',
    gender: 'Female',
    stats: { badminton: 78, carroms: 85, cricket: 72, football: 68, tt: 90 }
  },
  {
    id: 'p12',
    name: 'Sam "Stack Overflow" Scholar',
    role: 'Troubleshooting & Search',
    skillRating: 91,
    basePrice: 95000,
    status: 'AVAILABLE',
    photoUrl: '📚',
    gender: 'Male',
    stats: { badminton: 70, carroms: 95, cricket: 88, football: 82, tt: 75 }
  },
  {
    id: 'p13',
    name: 'Emily "Bug Hunter" Watson',
    role: 'QA & Test Automation',
    skillRating: 93,
    basePrice: 115000,
    status: 'AVAILABLE',
    photoUrl: '🐛',
    gender: 'Female',
    stats: { badminton: 85, carroms: 92, cricket: 74, football: 70, tt: 96 }
  },
  {
    id: 'p14',
    name: 'Jessica "Jira Queen" Jones',
    role: 'Project Management & Timelines',
    skillRating: 90,
    basePrice: 95000,
    status: 'AVAILABLE',
    photoUrl: '📅',
    gender: 'Female',
    stats: { badminton: 80, carroms: 90, cricket: 68, football: 65, tt: 85 }
  },
  {
    id: 'p15',
    name: 'Zoe "Brainstorm" Miller',
    role: 'Product Strategy & UX',
    skillRating: 92,
    basePrice: 105000,
    status: 'AVAILABLE',
    photoUrl: '🧠',
    gender: 'Female',
    stats: { badminton: 88, carroms: 85, cricket: 72, football: 70, tt: 92 }
  },
  {
    id: 'p16',
    name: 'Daniel "Docker" Jenkins',
    role: 'DevOps & Infra Reliability',
    skillRating: 89,
    basePrice: 85000,
    status: 'AVAILABLE',
    photoUrl: '🐳',
    gender: 'Male',
    stats: { badminton: 72, carroms: 88, cricket: 85, football: 82, tt: 78 }
  },
  {
    id: 'p17',
    name: 'Sophia "Social Media" Spark',
    role: 'Branding & Public Relations',
    skillRating: 87,
    basePrice: 75000,
    status: 'AVAILABLE',
    photoUrl: '✨',
    gender: 'Female',
    stats: { badminton: 82, carroms: 80, cricket: 65, football: 75, tt: 90 }
  },
  {
    id: 'p18',
    name: 'Ryan "Keyboard Warrior" King',
    role: 'Speed Typing & Documentation',
    skillRating: 86,
    basePrice: 70000,
    status: 'AVAILABLE',
    photoUrl: '⌨️',
    gender: 'Male',
    stats: { badminton: 75, carroms: 85, cricket: 80, football: 88, tt: 76 }
  },
  {
    id: 'p19',
    name: 'Isabella "Icebreaker" Lopez',
    role: 'Culture & Employee Bonding',
    skillRating: 88,
    basePrice: 80000,
    status: 'AVAILABLE',
    photoUrl: '🧊',
    gender: 'Female',
    stats: { badminton: 84, carroms: 95, cricket: 70, football: 72, tt: 86 }
  },
  {
    id: 'p20',
    name: 'Tyler "Tea Master" Brooks',
    role: 'Pantry Logistics & Gossip',
    skillRating: 82,
    basePrice: 50000,
    status: 'AVAILABLE',
    photoUrl: '🍵',
    gender: 'Male',
    stats: { badminton: 78, carroms: 82, cricket: 75, football: 70, tt: 80 }
  },
  {
    id: 'p21',
    name: 'Lily "Lint Master" Cooper',
    role: 'Code Quality & Standardizer',
    skillRating: 91,
    basePrice: 100000,
    status: 'AVAILABLE',
    photoUrl: '🧹',
    gender: 'Female',
    stats: { badminton: 82, carroms: 96, cricket: 70, football: 68, tt: 92 }
  },
  {
    id: 'p22',
    name: 'Oliver "Overtime" Vance',
    role: 'Night Shift & Support Duty',
    skillRating: 85,
    basePrice: 65000,
    status: 'AVAILABLE',
    photoUrl: '🌃',
    gender: 'Male',
    stats: { badminton: 70, carroms: 85, cricket: 90, football: 85, tt: 72 }
  },
  {
    id: 'p23',
    name: 'Ava "Analytics" Patel',
    role: 'BI Dashboards & SQL queries',
    skillRating: 94,
    basePrice: 120000,
    status: 'AVAILABLE',
    photoUrl: '📈',
    gender: 'Female',
    falaLeague: 'Second Place',
    stats: { badminton: 86, carroms: 92, cricket: 72, football: 75, tt: 94 }
  },
  {
    id: 'p24',
    name: 'Grace "Gratitude" Thompson',
    role: 'HR & Conflict Resolution',
    skillRating: 90,
    basePrice: 90000,
    status: 'AVAILABLE',
    photoUrl: '🤝',
    gender: 'Female',
    stats: { badminton: 80, carroms: 98, cricket: 65, football: 68, tt: 88 }
  },
  {
    id: 'p25',
    name: 'Henry "Hardware" Hughes',
    role: 'IT Setup & Fiber Repair',
    skillRating: 87,
    basePrice: 75000,
    status: 'AVAILABLE',
    photoUrl: '🔌',
    gender: 'Male',
    stats: { badminton: 74, carroms: 82, cricket: 88, football: 85, tt: 78 }
  },
  {
    id: 'p26',
    name: 'Mia "Meeting Scheduler" Young',
    role: 'Calendar Optimization',
    skillRating: 88,
    basePrice: 80000,
    status: 'AVAILABLE',
    photoUrl: '🗓️',
    gender: 'Female',
    stats: { badminton: 82, carroms: 88, cricket: 68, football: 72, tt: 85 }
  },
  {
    id: 'p27',
    name: 'Ethan "Ethical Hacker" Ward',
    role: 'Cybersecurity & Auditing',
    skillRating: 95,
    basePrice: 130000,
    status: 'AVAILABLE',
    photoUrl: '🛡️',
    gender: 'Male',
    stats: { badminton: 72, carroms: 95, cricket: 92, football: 90, tt: 85 }
  },
  {
    id: 'p28',
    name: 'Chloe "Creative Writer" Kim',
    role: 'PR & Corporate Copywriting',
    skillRating: 89,
    basePrice: 85000,
    status: 'AVAILABLE',
    photoUrl: '✍️',
    gender: 'Female',
    stats: { badminton: 80, carroms: 88, cricket: 70, football: 72, tt: 88 }
  },
  {
    id: 'p29',
    name: 'Owen "Optimizer" Davis',
    role: 'Database Indexing & Caching',
    skillRating: 92,
    basePrice: 110000,
    status: 'AVAILABLE',
    photoUrl: '⚡',
    gender: 'Male',
    stats: { badminton: 74, carroms: 85, cricket: 88, football: 82, tt: 90 }
  },
  {
    id: 'p30',
    name: 'Natalie "Note Taker" Diaz',
    role: 'Documentation & Wiki Management',
    skillRating: 86,
    basePrice: 70000,
    status: 'AVAILABLE',
    photoUrl: '📝',
    gender: 'Female',
    stats: { badminton: 82, carroms: 88, cricket: 65, football: 60, tt: 85 }
  }
];
